# Generated by Django 4.1.7 on 2023-02-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
