# Generated by Django 4.1.7 on 2023-02-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Title',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
